### ISSUE TITLE
How to get the value from fans?

### ISSUE THREAD

**Issue by kapitanluffy** [abichinger/Rainmeter-HardwareMonitor#10]
How do I get the value from the fans?

![image](https://user-images.githubusercontent.com/485799/153986716-bb696390-4727-4bf7-a442-285ab360eddc.png)

**Comment by abichinger** [comment]
![image](https://user-images.githubusercontent.com/8122139/154049844-864fa5e6-32a4-4c39-88fd-30917ac44f62.png)

I was able to read the fan rpm of my system using the following measure:

```ini
[Fan5RPM]
Measure=Plugin
Plugin=OpenHardwareMonitor
HardwareName=Nuvoton NCT6797D
SensorName=Fan #5
```

In your case it should be:
```ini
[Fan5RPM]
Measure=Plugin
Plugin=OpenHardwareMonitor
HardwareName=ITE IT8665E
SensorName=Fan #5
```
