### ISSUE TITLE
Update the README so it includes new SensorType types

### ISSUE THREAD

**Issue by Uros-V** [abichinger/Rainmeter-HardwareMonitor#11]
Right now the README is referencing quite an old (2011) OHM [pdf ](http://openhardwaremonitor.org/wordpress/wp-content/uploads/2011/04/OpenHardwareMonitor-WMI.pdf )when it comes to SensorType:
SensorType=Voltage | Clock | Temperature | Load | Fan | Flow | Control | Level
Currently **Open** Hardware Monitor has the following sensor types:
```
  public enum SensorType {
    Voltage, // V
    Clock, // MHz
    Temperature, // °C
    Load, // %
    Fan, // RPM
    Flow, // L/h
    Control, // %
    Level, // %
    Factor, // 1
    Power, // W
    Data, // GB = 2^30 Bytes    
    SmallData, // MB = 2^20 Bytes
    Throughput, // MB/s = 2^20 Bytes/s
  }
```
New types: Power, Factor, Data, SmallData, Throughput. 
[OHM Source](https://github.com/openhardwaremonitor/openhardwaremonitor/blob/master/Hardware/ISensor.cs)

And currently **Libre** Hardware Monitor has the following sensor types:
```
    public enum SensorType
    {
        Voltage, // V
        Current, // A
        Power, // W
        Clock, // MHz
        Temperature, // °C
        Load, // %
        Frequency, // Hz
        Fan, // RPM
        Flow, // L/h
        Control, // %
        Level, // %
        Factor, // 1
        Data, // GB = 2^30 Bytes
        SmallData, // MB = 2^20 Bytes
        Throughput, // B/s
        TimeSpan, // Seconds 
        Energy // milliwatt-hour (mWh)
    }
```
Even more new types:  Current, Power, Frequency, Factor, Data, SmallData, Throughput, TimeSpan, Energy. 
[LHM Source](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/ISensor.cs)

Closed #2 issue probably wouldn't be an issue if people knew about all available types heh.
I've tried SmallData for GPU VRAM and your plugin works fine with LHM.
All the best.

**Comment by abichinger** [comment]
@Uros-V thanks for letting me know.

The README now includes links to the respective source files. (6e28d53534ccf4d8bb1317034e2a0e397c92a7e9)

BTW it is not necessary to provide the sensor type, if the sensor is uniquely determined by its name.
