### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by epinter** [abichinger/Rainmeter-HardwareMonitor#12]
Hi,

I'm creating a skin using this Plugin, and I see the documentation doesn't cover some common situations, like this:

![image](https://user-images.githubusercontent.com/1561280/165986410-8ed89f62-fd42-46d9-bc34-ee8e8d3af089.png)

To Rainmeter access the "Temperature 2", in this case is my motherboard temp. I thought I would use Motherboard type, but I have to use SuperIO. To know that I had to user powershell:

~~~
Get-WmiObject -namespace "root\LibreHardwareMonitor"  -query "select * from Hardware"|sort Name|ft Name,HardwareType,Identifier
~~~

Then

~~~
Get-WmiObject -namespace "root\LibreHardwareMonitor"  -query "select * from Sensor"|sort-object Identifier,Name|ft Name,Identifier,Index,Value

Name                           Identifier                  Index       Value
----                           ----------                  -----       -----
CPU Core                       /lpc/nct6798d/temperature/0     0         41
Temperature #1                 /lpc/nct6798d/temperature/1     1       41,5
Temperature #2                 /lpc/nct6798d/temperature/2     2         29
Temperature #3                 /lpc/nct6798d/temperature/3     3       26,5
Temperature #4                 /lpc/nct6798d/temperature/4     4          8
Temperature #5                 /lpc/nct6798d/temperature/5     5        -12
Temperature #6                 /lpc/nct6798d/temperature/6     6         24
~~~

In Rainmeter, this works:
`SensorName=Temperature #2`
This works too:
`SensorIndex=/lpc/nct6798d/temperature/2`
But this give me wrong temperature:
`SensorIndex=2`

To get "Temperature 2" using the index I have to use SensorIndex=0.

**Comment by abichinger** [comment]
Hello,

The `SensorIndex` is not needed if the `SensorName` is unique within the hardware.
SensorIndex=/lpc/nct6798d/temperature/2 will resolve to `0`, because the Plugin expects a number.

I added a simple example, on how to monitor a fan rpm sensor to the README.
Do you think that's sufficient?

**Comment by epinter** [comment]
The SensorIndex resetting to zero explains why worked for me...

The new doc on the README really helps, the example worked for me.

Thank you
