### ISSUE TITLE
How to pull Max values?

### ISSUE THREAD

**Issue by speaktoryan** [abichinger/Rainmeter-HardwareMonitor#13]
Tried troubleshooting on the Rainmeter discord, but cannot figure out how to pull in Max values from OpenHardwareMonitor.

I'd like to essentially leave everything as-is in the skin files, but add (Max: XC) for temps or (Max: Y%) for load percentages.

Example: If OpenHardwareMonitor shows me current CPU Package temps are 32C and Max are 72C, I want the skins to show CPU Temp___________32C (Max: 72C).

Is there a way to do this? Thanks!

**Comment by abichinger** [comment]
@speaktoryan, I just released [v2.2.0](https://github.com/abichinger/Rainmeter-HardwareMonitor/releases/tag/v2.2.0), which adds support for min/max values.
usage example: https://github.com/abichinger/Rainmeter-HardwareMonitor#measure-minmax-values

Please let me know if it works for you.
