### ISSUE TITLE
Unable to get hardware info

### ISSUE THREAD

**Issue by MattJaccino** [abichinger/Rainmeter-HardwareMonitor#17]
Everything shows "-1", my use of the plugin and the overlays included in the package.  The commands you have people run give me no output, but OHM is running.  Any ideas?

OHM 0.9.6

**Comment by abichinger** [comment]
Hey!

You mean these commands? 

```powershell
get-wmiobject -namespace root\OpenHardwareMonitor -query 'select * from hardware'
get-wmiobject -namespace root\OpenHardwareMonitor -query 'select * from sensor' 
```

If you get no output, it probably means that the WMI interface of OHM does not work correctly. Unfortunately I have no idea why this is happening. Have you tried [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) instead?

If you use LibreHardwareMonitor make sure to set `Namespace=LibreHardwareMonitor`

``` ini
[Measure]  
Measure=Plugin  
Plugin=OpenHardwareMonitor.dll
Namespace=LibreHardwareMonitor
...
```

**Comment by MattJaccino** [comment]
Thank you for getting back to me so quickly.  Yep, nothing with those.  Will try LHM and see if there's any fix.  Thanks again!

**Comment by MattJaccino** [comment]
Downloaded LHM, finally getting output from the powershell commands, but still a '-1' in the readings in Rainmeter

EDIT: Had to make some changes for the format of LHM.  Everything's working now.  Thank you so much

**Comment by MattJaccino** [comment]
Issue resolved by using LHM
