### ISSUE TITLE
'GPU' -> 'data' -> 'memory used' cannot be recognized in Rainmeter

### ISSUE THREAD

**Issue by DanyGee** [abichinger/Rainmeter-HardwareMonitor#2]
**#This works**
[MeasureGPUTemp]
Measure=Plugin
Plugin=Plugins\OpenHardwareMonitorPlugin.dll
Hardware=NVIDIA GeForce GTX 1080
Type=Temperatures
Sensor=GPU Core

**#This does not work**
[MeasureGPUMemTotal]
Measure=Plugin
Plugin=Plugins\OpenHardwareMonitorPlugin.dll
Hardware=NVIDIA GeForce GTX 1080
Type=Data
Sensor=GPU Memory Used

...and gives an error (two times):
---------------------------
Rainmeter
---------------------------
The requested sensor doesn't exist.  Check your Open Hardware
Monitor application and carefully copy the names for the hardware, type, and sensor
name into the inputs.
Hardware: 'NVIDIA GeForce GTX 1080'
Type: 'Data'
Sensor: 'GPU Memory Used'

---------------------------
OK   
---------------------------

Screenshot of OHM outputs and Rainmeter error message in attachment.
Any idea why this particular sensor is not working?
![ohm](https://cloud.githubusercontent.com/assets/26818551/24552801/358a118a-1628-11e7-8e9e-47b44aa78619.png)
![rmem](https://cloud.githubusercontent.com/assets/26818551/24552855/64b20cce-1628-11e7-9b92-6f479b4af5d7.png)

**Comment by wilmol** [comment]
Same issue, in Nov 2021!

**Comment by abichinger** [comment]
@wilmol can you check if this issue persists in the latest [release](https://github.com/abichinger/Rainmeter-HardwareMonitor/releases).
