### ISSUE TITLE
LibreHardwareMonitor support

### ISSUE THREAD

**Issue by mnaiman** [abichinger/Rainmeter-HardwareMonitor#4]
Hi,

it would be great to support fork LibreHardwareMonitor (more active develoment).
Only change is here 
private const string OpenHardwareMonitorNamespace = "root\\OpenHardwareMonitor";
to
private const string OpenHardwareMonitorNamespace = "root\\LibreHardwareMonitor";

Rest of API is same. So It could be variable in Sensor if it is Open or Libre.

Second thing - there are some types like ManagementObject which implements IDisposable. 
They should be in using statements to correctly free unmanaged resources and prevent memory leaks.

https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects

**Comment by abichinger** [comment]
@mnaiman thanks for your proposal.
I'm going to work on it.

> Second thing - there are some types like ManagementObject which implements IDisposable.
> They should be in using statements to correctly free unmanaged resources and prevent memory leaks.
>
> https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects

good to know :+1:

**Comment by mnaiman** [comment]
![image](https://user-images.githubusercontent.com/2264442/144582008-c9464cc1-aa94-4e38-a376-b11d945f7a5b.png)

Perfect :)
