### ISSUE TITLE
Cannot get Water Temp. from D5Next (Pump/Cooler)

### ISSUE THREAD

**Issue by c4tz** [abichinger/Rainmeter-HardwareMonitor#8]
Hey @abichinger,

thank you for this fine piece of software! Today, I were trying to display some loads and temps for my system in Rainmeter and got everything working smoothly, except for my water pump.

It is listed in LibreHardwareMonitor and after I looked around a bit, I found that the pump also indeed supported by LibreHardwareMonitorLib: [Class](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Controller/AquaComputer/D5Next.css) | [Group entry](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Controller/AquaComputer/AquaComputerGroup.cs#L29) | ["Cooler" HardwareType](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/HardwareType.cs)

Here is the `.ini`-snippet from Rainmeter I used:

```ini
[WaterTemp]
Measure=Plugin
Plugin=OpenHardwareMonitor
Namespace=LibreHardwareMonitor
HardwareName=D5Next
;HardwareType=Cooler
SensorType=Temperature
SensorName=Water Temperature
MinValue=0
MaxValue=100

[WaterMeter]
Meter=String
Text=Water Temp: [WaterTemp:1]°C
```

I tried both `HardwareName=D5Next` and `HardwareType=Cooler`, but always get this error (similar for `Cooler`):

```
[DEBUG] Sensor Query: SELECT * FROM Sensor where Parent='/\\?\hid#vid_0c70&pid_f00e&mi_01#9&226c2ca2&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}' and SensorType='Temperature' and name='Water Temperature' (custom\rainmeter.ini - [WaterTemp])
[DEBUG] Hardware Identifier: /\\?\hid#vid_0c70&pid_f00e&mi_01#9&226c2ca2&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (custom\rainmeter.ini - [WaterTemp])
[DEBUG] Hardware Query: SELECT * FROM Hardware where name='D5Next' (custom\rainmeter.ini - [WaterTemp])
[DEBUG] Hardware(type, name, index): (, D5Next, 0), Sensor(type, name, index): (Temperature, Water Temperature, 0) (custom\rainmeter.ini - [WaterTemp])
[DEBUG] System.Management.ManagementException: Invalid request. (<-- Roughly translated from "Die Anfrage ist ungültig." )
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at RainmeterOHM.WMIQuery.GetAt(Int32 index)
   at RainmeterOHM.Measure.Reload(API rm) (custom\rainmeter.ini - [WaterTemp])
```

Do you maybe have an idea what could cause this problem?

**Comment by abichinger** [comment]
Hello @c4tz,

the id `/\\?\hid#vid_0c70&pid_f00e&mi_01#9&226c2ca2&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}` of your water pump has probably some values, which should be escaped.

Can you please provide more information by executing the following powershell commands:

```powershell
get-wmiobject -namespace root\LibreHardwareMonitor -query 'select * from sensor' > sensor.txt
get-wmiobject -namespace root\LibreHardwareMonitor -query 'select * from hardware' > hardware.txt
```

**Comment by c4tz** [comment]
Thank you for the fast response! Sure, these are the output files:

[hardware.txt](https://github.com/abichinger/Rainmeter-HardwareMonitor/files/7779636/hardware.txt)
[sensor.txt](https://github.com/abichinger/Rainmeter-HardwareMonitor/files/7779637/sensor.txt)

**Comment by abichinger** [comment]
Thank you for the logs :)

Unfortunately I can't replicate your error on my system. 
Can you please test this version for me.
[OpenHardwareMonitor_2.1.2.rmskin.zip](https://github.com/abichinger/Rainmeter-HardwareMonitor/files/7779983/OpenHardwareMonitor_2.1.2.rmskin.zip)

**Comment by c4tz** [comment]
I did test it, but sadly the logs are exactly the same as before.  I also verified that the new version `2.1.2` was loaded:

![image](https://user-images.githubusercontent.com/4035667/147469717-2f52385e-f0d3-4033-b404-6f20704bc3aa.png)
